[package]
name = "kardavx/cyberchuj"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Maid = "nightcycle/maid@1.1.4"
Bridgenet2 = "ffrostflame/bridgenet2@1.0.0"
Promise = "lukadev-0/typed-promise@4.0.2"
ProfileService = "brittonfischer/profileservice@2.1.5"
Reflex = "littensy/reflex@4.3.1"
Signal = "sleitnick/signal@2.0.1"
CameraShaker = "brittonfischer/camerashaker@0.1.0"
spring = "murtlatif/spring@0.1.2"

# React
React = "jsdotlua/react@17.0.4"
ReactRoblox = "jsdotlua/react-roblox@17.0.4"