return {
	Arrested = {
		{ id = 15822691305, dialogId = "TOC_ARRESTED_RESONSE_01" },
		{ id = 15822693068, dialogId = "TOC_ARRESTED_RESONSE_02" },
		{ id = 15822694318, dialogId = "TOC_ARRESTED_RESONSE_03" },
	},
	Prefix = {
		{ id = 15823391200, dialogId = "TOC_PREFIX_01" },
		{ id = 15823391443, dialogId = "TOC_PREFIX_02" },
		{ id = 15823391623, dialogId = "TOC_PREFIX_03" },
	},
} :: { [string]: { { id: number, dialogId: string } } }
