return {
	animationInfo = {
		Idle = {
			Looped = true,
			Priority = Enum.AnimationPriority.Action,
		},
		Aim = {
			Looped = true,
			Priority = Enum.AnimationPriority.Action,
		},
		AimShoot = {
			Looped = false,
			Priority = Enum.AnimationPriority.Action2,
		},
		Shoot = {
			Looped = false,
			Priority = Enum.AnimationPriority.Action2,
		},
		Reload = {
			Looped = false,
			Priority = Enum.AnimationPriority.Action3,
		},
	},
}
